# Defines the options for building the project on Windows with ci.appveyor.com
# For more configuration options, see https://www.appveyor.com/docs/build-configuration.
# Note that we're calling a customized version of appveyor-tool.ps1 to get R-stable
# and to call a customized version of travis-tool.sh which uses GRAN+CRAN by default.

# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

environment:
  R_VERSION: stable
  USE_RTOOLS: true
  R_CHECK_ARGS: --no-build-vignettes --no-manual --no-multiarch
  R_BUILD_ARGS: --no-build-vignettes --no-manual
  R_INSTALL_ARGS: --no-multiarch
  GITHUB_PAT:
    secure: 03KIbW8uRiLt7B5/qFLzuKKx2t1ElXoZeFxuwVftpkzL4+A2cGPe4wTkKAwOOEb1
  global:
    WARNINGS_ARE_ERRORS: 1

build_script:
  - R --version
  - Rscript -e "install.packages(c('smwrData', 'smwrBase', 'smwrGraphs', 'smwrStats', 'smwrQW', 'rloadest', 'unitted'), repos=c('https://owi.usgs.gov/R', 'https://cran.rstudio.com'))"
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
