
environment:
  R_CHECK_ARGS: --no-build-vignettes --no-manual --no-multiarch
  R_BUILD_ARGS: --no-build-vignettes --no-manual
  R_INSTALL_ARGS: --no-multiarch
 

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
  cmd: echo "options(repos = c(CRAN='http://cran.r-project.org'))" > .Rprofile

install:
  ps: Bootstrap

build_script:
  - R --version
  - travis-tool.sh install_github appling/unitted@v0.2.5 USGS-R/smwrData@v1.1.0 USGS-R/smwrBase@v1.1.0 USGS-R/smwrGraphs@v1.1.0 USGS-R/smwrStats@v0.7.2 USGS-R/smwrQW@v0.7.5 USGS-R/rloadest@v0.4.2
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
